sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t tareksaleh5/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tareksaleh5/docker-react npm run test